name: Update Response JSON

on:
  schedule:
    - cron: '0 */2 * * *'  # Run every 2 hours
  workflow_dispatch:       # Allow manual triggering

jobs:
  update-response:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Check if response.json exists
      id: check_file
      run: |
        if [ -f "response.json" ]; then
          echo "::set-output name=file_exists::true"
        else
          echo "::set-output name=file_exists::false"
        fi
    
    - name: Call API and Process Response
      run: |
        curl -sS -o temp.csv https://www.vpngate.net/api/iphone/
        tail -n +2 temp.csv > temp_without_header.csv
        python process_csv.py
        mv processed_response.json response.json
        
    - name: Create response.json if it doesn't exist
      if: steps.check_file.outputs.file_exists == 'false'
      run: |
        echo '{}' > response.json
    
    - name: Commit and Push Changes
      if: github.event_name != 'workflow_dispatch'  # Skip commit and push for manual trigger
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add response.json
        git commit -m "Update response.json - $(date +'%Y-%m-%d %H:%M:%S')"
        git push
